### ISSUE TITLE
Slash division depreciated; should use math.div()

### ISSUE THREAD

**Issue by tbredin** [DZakh/Custom-gutters-bootstrap-plugin#1]
Tried using this but it throws an error, which I think is probably expected in more recent versions of sass:

> Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
> Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
> 
> Recommendation: math.div($grid-gutter-width, 2) or calc($grid-gutter-width / 2)
> 
> More info and automated migrator: https://sass-lang.com/d/slash-div

Easy to fix! See below

```
@use "sass:math";

$grid-gutter-widths: (
  xs: 30px,
) !default;

@each $grid-breakpoint, $grid-gutter-width in $grid-gutter-widths {
  @include media-breakpoint-up($grid-breakpoint) {
    $grid-gutter-half-width: math.div($grid-gutter-width, 2);
    .row:not(.no-gutters) {
      margin-right: -$grid-gutter-half-width;
      margin-left: -$grid-gutter-half-width;
    }
    .row:not(.no-gutters) > .col,
    .row:not(.no-gutters) > [class*="col-"] {
      padding-right: $grid-gutter-half-width;
      padding-left: $grid-gutter-half-width;
    }
  }
}
```

**Comment by DZakh** [comment]
Thanks for letting me know. I've published a new version with a fix. Could you try it?
I don't use sass for something like 3 years already, so I can't really test it.
